@base_url = http://localhost:5096

GET {{base_url}}/api/weatherforecast/GetWeatherForecast
Accept: application/json

###

GET {{base_url}}/api/cities/
Accept: application/json

###
GET {{base_url}}/api/cities/
Accept: application/xml

###

@cityId = 1
GET {{base_url}}/api/cities/{{cityId}}
Accept: application/json

###

@pointOfInterest = 4
GET {{base_url}}/api/cities/{{cityId}}/pointofinterest/{{pointOfInterest}}
Accept: application/json

###

POST {{base_url}}/api/cities/{{cityId}}/pointofinterest/
content-type: application/json
{
  "id" : 99,
  "name": "BHEL",
  "description": "Bharat heavy electronics limited"
}

###